ARG BASE_IMAGE
FROM ${BASE_IMAGE}
LABEL maintainer="Masaki Muranaka <monaka@monami-ya.com>"

RUN sudo apt-get update \
 && sudo apt-get upgrade -y \
 && curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash - \
 && sudo apt-get install -y nodejs \
 && sudo npm i -g expo-cli
