ARG BASE_IMAGE
FROM ${BASE_IMAGE}
LABEL maintainer="Masaki Muranaka <monaka@monami-ya.com>"

RUN sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y npm \
 && sudo npm i -g expo-cli
